/**
 * GENERATED by scripts/ncct-import.mjs — do not edit by hand.
 *
 * Real head-CT pixels (CQ500, de-identified) windowed to W 80 / L 40 and written as
 * PNG slices under /public/ncct. The patient named on screen is always the §8
 * sample-kit patient the case belongs to; the source study id below is
 * provenance, never an identity.
 *
 * `truth` is the study's own ground-truth label row. Every AI finding the
 * console and the report show is derived from it, so nothing on screen
 * contradicts the pixels behind it.
 */

export interface NcctTruth {
  ich: boolean
  iph: boolean
  ivh: boolean
  sdh: boolean
  edh: boolean
  sah: boolean
  massEffect: boolean
  midlineShift: boolean
}

export interface NcctStudy {
  /** The folder under /ncct. Equals the stroke case id where there is one. */
  key: string
  /** The stroke case this study stands behind — absent for a CT outside the pathway. */
  strokeCaseId?: string
  patientId: string
  /** Slice files are <base>ncct/<key>/slice-01.png … slice-NN.png */
  slices: number
  rows: number
  columns: number
  sliceThickness: number
  kvp: number
  seriesDescription: string
  /** How many images the source series held before subsampling. */
  seriesTotal: number
  /** De-identified source id. Provenance only. */
  sourcePatientId: string
  manufacturer: string
  truth: NcctTruth
}

export const NCCT_WINDOW = { width: 80, level: 40 } as const

export const NCCT_STUDIES: Record<string, NcctStudy> = {
  '0141': {
    key: '0141',
    strokeCaseId: '0141',
    patientId: 'SD-P-05',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 0.625,
    kvp: 140,
    seriesDescription: 'Thin Plain',
    seriesTotal: 256,
    sourcePatientId: 'CQ500-CT-11',
    manufacturer: '',
    truth: { ich: false, iph: false, ivh: false, sdh: false, edh: false, sah: false, massEffect: false, midlineShift: false },
  },
  '0140': {
    key: '0140',
    strokeCaseId: '0140',
    patientId: 'SD-P-03',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 3,
    kvp: 120,
    seriesDescription: 'Plain 3mm',
    seriesTotal: 52,
    sourcePatientId: 'CQ500-CT-224',
    manufacturer: '',
    truth: { ich: false, iph: false, ivh: false, sdh: false, edh: false, sah: false, massEffect: false, midlineShift: false },
  },
  '0137': {
    key: '0137',
    strokeCaseId: '0137',
    patientId: 'SD-P-12',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 0.625,
    kvp: 120,
    seriesDescription: 'PLAIN THIN',
    seriesTotal: 224,
    sourcePatientId: 'CQ500-CT-10',
    manufacturer: '',
    truth: { ich: true, iph: true, ivh: false, sdh: false, edh: false, sah: false, massEffect: false, midlineShift: false },
  },
  '0138': {
    key: '0138',
    strokeCaseId: '0138',
    patientId: 'SD-P-13',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 1,
    kvp: 120,
    seriesDescription: 'Plain THIN',
    seriesTotal: 166,
    sourcePatientId: 'CQ500-CT-366',
    manufacturer: '',
    truth: { ich: false, iph: false, ivh: false, sdh: false, edh: false, sah: false, massEffect: true, midlineShift: true },
  },
  '0142': {
    key: '0142',
    strokeCaseId: '0142',
    patientId: 'SD-P-14',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 0.625,
    kvp: 120,
    seriesDescription: 'PLAIN THIN',
    seriesTotal: 272,
    sourcePatientId: 'CQ500-CT-48',
    manufacturer: '',
    truth: { ich: true, iph: true, ivh: true, sdh: false, edh: false, sah: true, massEffect: true, midlineShift: true },
  },
  'N-061': {
    key: 'N-061',
    patientId: 'SD-P-11',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 3,
    kvp: 120,
    seriesDescription: 'Plain 3mm',
    seriesTotal: 58,
    sourcePatientId: 'CQ500-CT-61',
    manufacturer: '',
    truth: { ich: true, iph: false, ivh: false, sdh: true, edh: false, sah: false, massEffect: true, midlineShift: true },
  },
  'N-025': {
    key: 'N-025',
    patientId: 'SD-P-15',
    slices: 12,
    rows: 512,
    columns: 512,
    sliceThickness: 5,
    kvp: 140,
    seriesDescription: '5/5mm Plain',
    seriesTotal: 12,
    sourcePatientId: 'CQ500-CT-25',
    manufacturer: '',
    truth: { ich: false, iph: false, ivh: false, sdh: false, edh: false, sah: false, massEffect: false, midlineShift: false },
  },
  'N-050': {
    key: 'N-050',
    patientId: 'SD-P-16',
    slices: 8,
    rows: 512,
    columns: 512,
    sliceThickness: 0.625,
    kvp: 120,
    seriesDescription: '0.625mm',
    seriesTotal: 8,
    sourcePatientId: 'CQ500-CT-50',
    manufacturer: '',
    truth: { ich: false, iph: false, ivh: false, sdh: false, edh: false, sah: false, massEffect: false, midlineShift: false },
  },
}

/**
 * The slice path a viewer requests. 1-based, zero-padded to two digits. Built
 * on Vite's base URL so the app works when it is served from a sub-path.
 */
export function slicePath(key: string, index: number): string {
  return `${import.meta.env.BASE_URL}ncct/${key}/slice-${String(index).padStart(2, '0')}.png`
}
