/**
 * GENERATED by scripts/ncct-import.mjs — do not edit by hand.
 *
 * Real head-CT pixels (CQ500, de-identified) windowed to W 80 / L 40 and written as
 * PNG slices under /public/ncct. The patient named on screen is always the §8
 * sample-kit patient the case belongs to; the source study id below is
 * provenance, never an identity.
 *
 * `truth` is the study's own ground-truth label row. Every AI finding the
 * console and the report show is derived from it, so nothing on screen
 * contradicts the pixels behind it.
 */

export interface NcctTruth {
  ich: boolean
  iph: boolean
  ivh: boolean
  sdh: boolean
  edh: boolean
  sah: boolean
  massEffect: boolean
  midlineShift: boolean
}

export interface NcctStudy {
  /** The §8 stroke case this study stands behind. */
  caseId: string
  patientId: string
  /** Slice files are /ncct/<caseId>/slice-01.png … slice-NN.png */
  slices: number
  rows: number
  columns: number
  sliceThickness: number
  kvp: number
  seriesDescription: string
  /** How many images the source series held before subsampling. */
  seriesTotal: number
  /** De-identified source id. Provenance only. */
  sourcePatientId: string
  manufacturer: string
  truth: NcctTruth
}

export const NCCT_WINDOW = { width: 80, level: 40 } as const

export const NCCT_STUDIES: Record<string, NcctStudy> = {
  '0141': {
    caseId: '0141',
    patientId: 'SD-P-05',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 0.625,
    kvp: 140,
    seriesDescription: 'Thin Plain',
    seriesTotal: 256,
    sourcePatientId: 'CQ500-CT-11',
    manufacturer: '',
    truth: { ich: false, iph: false, ivh: false, sdh: false, edh: false, sah: false, massEffect: false, midlineShift: false },
  },
  '0140': {
    caseId: '0140',
    patientId: 'SD-P-08',
    slices: 28,
    rows: 512,
    columns: 512,
    sliceThickness: 3,
    kvp: 120,
    seriesDescription: 'Plain 3mm',
    seriesTotal: 52,
    sourcePatientId: 'CQ500-CT-224',
    manufacturer: '',
    truth: { ich: false, iph: false, ivh: false, sdh: false, edh: false, sah: false, massEffect: false, midlineShift: false },
  },
}

/** The slice path a viewer requests. 1-based, zero-padded to two digits. */
export function slicePath(caseId: string, index: number): string {
  return `/ncct/${caseId}/slice-${String(index).padStart(2, '0')}.png`
}
